# Sonis 14 pathways

- The authors performed an RNA microarray on the peripheral monocytes of 5 adult oncology patients before and after chemoradiation therapy. Patients in this study received both paclitaxel and radiation therapy
- 14 Canonical Pathways from Sonis et al. 2006 paper

In [1]:
import requests
import json  # for enrichment analysis 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from Bio import Entrez

In [2]:
# The 14 Pathways Queried from MsigDB Database

if __name__ == "__main__":
    PATH_NAMES = ["KEGG_NITROGEN_METABOLISM",
                  "KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY",
                  "REACTOME_TNFR1_INDUCED_NFKAPPAB_SIGNALING_PATHWAY",
                  "BIOCARTA_BCR_PATHWAY",
                  "REACTOME_PI3K_AKT_SIGNALING_IN_CANCER",
                  "REACTOME_G2_M_DNA_DAMAGE_CHECKPOINT",
                  "WP_P38_MAPK_SIGNALING_PATHWAY",
                  "WP_WNTBETACATENIN_SIGNALING_PATHWAY_IN_LEUKEMIA",
                  "REACTOME_INTEGRIN_SIGNALING",
                  "KEGG_VEGF_SIGNALING_PATHWAY",
                  "WP_IL6_SIGNALING_PATHWAY",
                  "REACTOME_DEATH_RECEPTOR_SIGNALLING",
                  "REACTOME_JNK_C_JUN_KINASES_PHOSPHORYLATION_AND_ACTIVATION_MEDIATED_BY_ACTIVATED_HUMAN_TAK1",
                  "GOBP_GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY",
                  ]

- 13 pathways came from MsigDB c2 database

In [3]:
df1 = pd.read_json('data/c2_msigdb.json')

In [4]:
#Examine the top 5 rows of the dataframe
df1.head(5)

,BIOCARTA_41BB_PATHWAY,BIOCARTA_ACE2_PATHWAY,BIOCARTA_ACETAMINOPHEN_PATHWAY,BIOCARTA_ACH_PATHWAY,BIOCARTA_ACTINY_PATHWAY,BIOCARTA_AGPCR_PATHWAY,BIOCARTA_AGR_PATHWAY,BIOCARTA_AHSP_PATHWAY,BIOCARTA_AKAP13_PATHWAY,BIOCARTA_AKAP95_PATHWAY,...,WP_VITAMIN_D_METABOLISM,WP_VITAMIN_D_RECEPTOR_PATHWAY,WP_VITAMIN_DSENSITIVE_CALCIUM_SIGNALING_IN_DEPRESSION,WP_WHITE_FAT_CELL_DIFFERENTIATION,WP_WNT_SIGNALING,WP_WNT_SIGNALING_IN_KIDNEY_DISEASE,WP_WNT_SIGNALING_PATHWAY,WP_WNT_SIGNALING_PATHWAY_AND_PLURIPOTENCY,WP_WNTBETACATENIN_SIGNALING_PATHWAY_IN_LEUKEMIA,WP_ZINC_HOMEOSTASIS
systematicName,M2064,M12950,M22024,M16884,M7825,M19829,M6220,M19553,M17668,M5731,...,M39352,M39718,M39831,M39333,M39669,M39699,M39721,M39387,M39407,M39377
pmid,,,,,,,,,,,...,,,,,,,,,,
exactSource,,,,,,,,,,,...,WP1531,WP2877,WP4698,WP4149,WP428,WP4150,WP363,WP399,WP3658,WP3529
geneSymbols,"[ATF2, CHUK, IFNG, IKBKB, IL2, IL4, JUN, MAP3K...","[ACE, ACE2, AGT, AGTR1, AGTR2, CMA1, COL4A1, C...","[CYP1A2, CYP2E1, NR1I3, PTGS1, PTGS2]","[AKT1, BAD, CHRNB1, CHRNG, FASLG, FOXO3, MUSK,...","[ABI2, ACTA1, NCK1, NCKAP1, NTRK1, PIR, PSMA7,...","[ARRB1, GNAS, GRK4, PRKACB, PRKACG, PRKAR1A, P...","[ACTA1, AGRN, ARHGEF6, CDC42, CHRM1, CHRNA1, C...","[AHSP, ALAD, ALAS1, ALAS2, CPOX, FECH, GATA1, ...","[AKAP13, GNA12, LPAR1, LPAR2, LPAR3, PRKACB, P...","[AKAP8, CCNB1, CDK1, DDX5, NCAPD2, PPP2CA, PRK...",...,"[CYP24A1, CYP27A1, CYP27B1, CYP2R1, DHCR7, GC,...","[ABCA11P, ABCB1, ABCD1, ADAMTS5, ADGRE5, ADRA1...","[ATP2B1, ATP2B2, ATP2B3, ATP2B4, BCL2, CACNA1C...","[CEBPA, CEBPB, CEBPD, CREB1, CTNNA1, DDIT3, EB...","[APC, AXIN1, CAMK2A, CAMK2B, CAMK2D, CAMK2G, C...","[CTNNB1, DVL1, DVL2, DVL3, FZD1, FZD2, FZD3, F...","[AKT1, APC, ARRB2, AXIN1, AXIN2, BCL9, CCND1, ...","[APC, AXIN1, AXIN2, CCND1, CCND2, CCND3, CD44,...","[AKT1, APC, AXIN2, BCL9, CCND1, CSNK1A1, CTNNB...","[MT1A, MT1B, MT1E, MT1F, MT1G, MT1H, MT1L, MT1..."
msigdbURL,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...

-  1 pathway (Glutamate receptor pathway) came from MsigDB c5 database:

In [5]:
df2 = pd.read_json("data/c5_msigdb.json")

In [6]:
#Examine the top 5 rows of df2
df2.head(5)

,GOBP_10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS,GOBP_2_OXOGLUTARATE_METABOLIC_PROCESS,GOBP_2FE_2S_CLUSTER_ASSEMBLY,GOBP_3_PHOSPHOADENOSINE_5_PHOSPHOSULFATE_BIOSYNTHETIC_PROCESS,GOBP_3_PHOSPHOADENOSINE_5_PHOSPHOSULFATE_METABOLIC_PROCESS,GOBP_3_UTR_MEDIATED_MRNA_DESTABILIZATION,GOBP_3_UTR_MEDIATED_MRNA_STABILIZATION,GOBP_5_PHOSPHORIBOSE_1_DIPHOSPHATE_METABOLIC_PROCESS,GOBP_5S_CLASS_RRNA_TRANSCRIPTION_BY_RNA_POLYMERASE_III,GOBP_ABSCISSION,...,HP_XANTHOMATOSIS,HP_XEROSTOMIA,HP_Y_LINKED_INHERITANCE,HP_Y_SHAPED_METACARPALS,HP_YELLOW_BROWN_DISCOLORATION_OF_THE_TEETH,HP_YELLOW_WHITE_LESIONS_OF_THE_MACULA,HP_YELLOW_WHITE_LESIONS_OF_THE_RETINA,HP_YOUNG_ADULT_ONSET,HP_ZOLLINGER_ELLISON_SYNDROME,HP_ZONULAR_CATARACT
systematicName,M29088,M15857,M23654,M23898,M23897,M24263,M11060,M29212,M29174,M22599,...,M35062,M34609,M35297,M36796,M36819,M38383,M38385,M37856,M35606,M37696
pmid,,,,,,,,,,,...,,,,,,,,,,
exactSource,GO:0009256,GO:0006103,GO:0044571,GO:0050428,GO:0050427,GO:0061158,GO:0070935,GO:0046391,GO:0042791,GO:0009838,...,HP:0000991,HP:0000217,HP:0001450,HP:0006042,HP:0006286,HP:0030500,HP:0030506,HP:0011462,HP:0002044,HP:0010920
geneSymbols,"[AASDHPPT, ALDH1L1, ALDH1L2, MTHFD1, MTHFD1L, ...","[AADAT, ADHFE1, D2HGDH, DLST, GOT1, GOT2, GPT2...","[BOLA2, BOLA2B, GLRX3, GLRX5, HSCB, NFS1]","[PAPSS1, PAPSS2, SLC26A1, SLC26A2, SLC35B2, SL...","[ABHD14B, BPNT1, ENPP1, PAPSS1, PAPSS2, SLC26A...","[CPEB3, DHX36, DND1, HNRNPD, KHSRP, MOV10, PLE...","[ANGEL2, BOLL, DAZ1, DAZ2, DAZ3, DAZ4, DAZL, E...","[PRPS1, PRPS1L1, PRPS2, PRPSAP1, PRPSAP2, PYGL]","[GTF3C1, GTF3C2, GTF3C3, GTF3C4, GTF3C5, GTF3C6]","[AURKB, CHMP4C, IST1, SPART, VPS4A, ZFYVE19]",...,"[ABCA1, ABCG5, ABCG8, APOA1, APOA2, APOA5, APO...","[ANG, ANXA11, ATXN2, C9orf72, CAV1, CCN2, CCNF...","[BPY2, CDY1, CDY2A, DAZ1, DAZ2, DAZ3, DDX3Y, H...","[CPLANE1, FAM149B1, GLI3, HOXD13, INTU, KIAA07...","[DLX3, ENAM, FAM20A, ITGB6, RELT, ROGDI, SATB1...","[ABCA4, APOE, BEST1, CFH, CFHR1, CFHR3, CFI, C...","[ABCA4, ABCC6, AGXT, ALMS1, APOE, BEST1, C1QTN...","[ABCA4, ACTG1, ALDH5A1, ATP13A2, ATP1A3, CASQ2...","[ATRX, CDKN1A, CDKN1B, CDKN2B, CDKN2C, DAXX, M...","[BAP1, BEST1, BFSP1, CFAP410, CHMP4B, CRYBA1, ..."
msigdbURL,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...,https://www.gsea-msigdb.org/gsea/msigdb/cards/...

- Select columns by pathway of interest

In [7]:
dict = {}
for p in PATH_NAMES:
    if p in df1.columns:
        df_1 = df1[p]
        dict[p] = df_1.iloc[3,]
    else:
        df_2 = df2[p]
        dict[p] = df_2.iloc[3,]

In [8]:
sonis_df = pd.DataFrame({"pathway":dict.keys(),"genes":dict.values()})
sonis_df["type"] = "sonis_set"

## Using Enrichr for Gene Set reconcilliation 

-  'KEGG_2021_Human','Reactome_2016', 'BioPlanet_2019', 'WikiPathways_2019_Human', "Human_Phenotype_Ontology", and "GO_Biological_Process_2021"

In [36]:
library = ['Reactome_2016', 'KEGG_2021_Human','BioPlanet_2019','WikiPathways_2019_Human', 'Human_Phenotype_Ontology', 'GO_Biological_Process_2021']

In [37]:
import gseapy as gp
def get_enrichr_txt(input_list, library):
    enr = gp.enrichr(gene_list=input_list,
                     gene_sets= library,
                     organism='Human', # don't forget to set organism to the one you desired! e.g. Yeast
                     description="sonis_pathways",
                     no_plot=True,
                     cutoff = 0.05 #  Show enriched terms which Adjusted P-value < cutoff.
                    )
    df = enr.results
    return df

In [38]:
df_list = []
for sublist in dict.values():    
    df_enr = get_enrichr_txt(sublist, library).sort_values(["Combined Score"], ascending=False).iloc[0:1]
    df_enr["original size"] = len(sublist)
    new_df = df_enr.drop(["Adjusted P-value", "Old P-value", "Old Adjusted P-value", "Odds Ratio", "P-value", "Combined Score"], axis=1 )
    df_list.append(new_df)
    
summary_df = pd.concat(df_list)

In [39]:
summary_df.to_excel("./gene_set_results/enrichr_sonis.xlsx")

In [40]:
summary_df["original_set"] = dict.keys()
summary_df.rename(columns = {"Gene_set":"library", "Term":"term", "Overlap":"overlap"}, inplace=True)
summary_df.loc[:,["library","term","original_set","overlap","original size"]]

,library,term,original_set,overlap,original size
0,BioPlanet_2019,Nitrogen metabolism,KEGG_NITROGEN_METABOLISM,23/23,23
0,BioPlanet_2019,Toll-like receptor signaling pathway regulation,KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY,102/142,102
2,Reactome_2016,TNFR1-induced NFkappaB signaling pathway Homo ...,REACTOME_TNFR1_INDUCED_NFKAPPAB_SIGNALING_PATHWAY,25/26,30
1,BioPlanet_2019,Antigen-activated B-cell receptor generation o...,BIOCARTA_BCR_PATHWAY,33/211,33
0,Reactome_2016,PI3K/AKT Signaling in Cancer Homo sapiens R-HS...,REACTOME_PI3K_AKT_SIGNALING_IN_CANCER,86/86,105
21,Reactome_2016,Chk1/Chk2(Cds1) mediated inactivation of Cycli...,REACTOME_G2_M_DNA_DAMAGE_CHECKPOINT,12/12,95
0,WikiPathways_2019_Human,p38 MAPK Signaling Pathway WP400,WP_P38_MAPK_SIGNALING_PATHWAY,34/34,34
0,WikiPathways_2019_Human,Wnt/beta-catenin Signaling Pathway in Leukemia...,WP_WNTBETACATENIN_SIGNALING_PATHWAY_IN_LEUKEMIA,26/26,26
0,Reactome_2016,Integrin alphaIIb beta3 signaling Homo sapiens...,REACTOME_INTEGRIN_SIGNALING,27/27,27
0,BioPlanet_2019,VEGF signaling pathway,KEGG_VEGF_SIGNALING_PATHWAY,76/76,76
0,WikiPathways_2019_Human,IL-6 signaling pathway WP364,WP_IL6_SIGNALING_PATHWAY,43/43,43
9,BioPlanet_2019,Cell death signaling by NRIF in the nucleus,REACTOME_DEATH_RECEPTOR_SIGNALLING,16/16,141
0,GO_Biological_Process_2021,JNK cascade (GO:0007254),REACTOME_JNK_C_JUN_KINASES_PHOSPHORYLATION_AND...,22/41,22
0,GO_Biological_Process_2021,glutamate receptor signaling pathway (GO:0007215),GOBP_GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY,37/37,52

## Add Extra Genes from Enrichr

In [23]:
def extra_genes(lib, enr_path, s_path):
    with open (f"Enrichr\{lib}") as f:
        for line in f.readlines():
            line = line.split("\t")
            if line[0] == enr_path:
                enr_list = line[2:-1]
                ext = set(dict[s_path]).union(set(enr_list))
                print(enr_path," added : ", len(ext)-len(set(dict[s_path])))
                ext = [x for x in ext]
                return ext

In [24]:
new_toll = extra_genes("BioPlanet_2019.txt","Toll-like receptor signaling pathway regulation","KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY")
new_int = extra_genes("BioPlanet_2019.txt","Platelet aggregation (plug formation)","REACTOME_INTEGRIN_SIGNALING")
new_wnt = extra_genes("BioPlanet_2019.txt","Inactivation of GSK3 by Akt causes accumulation of beta-catenin in alveolar macrophages","WP_WNTBETACATENIN_SIGNALING_PATHWAY_IN_LEUKEMIA")
new_jnk = extra_genes("GO_Biological_Process_2021.txt","JNK cascade (GO:0007254)","REACTOME_JNK_C_JUN_KINASES_PHOSPHORYLATION_AND_ACTIVATION_MEDIATED_BY_ACTIVATED_HUMAN_TAK1")

Toll-like receptor signaling pathway regulation  added :  40
Platelet aggregation (plug formation)  added :  10
Inactivation of GSK3 by Akt causes accumulation of beta-catenin in alveolar macrophages  added :  20
JNK cascade (GO:0007254)  added :  19

- Toll-like receptor signaling pathway regulation  added :  40
- Platelet aggregation (plug formation)  added :  10
- Inactivation of GSK3 by Akt causes accumulation of beta-catenin in alveolar macrophages  added :  20
- JNK cascade (GO:0007254)  added :  19

In [27]:
#update sonis pathways with the Enrichr added gene sets 
dict["KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY"] = new_toll
dict["REACTOME_JNK_C_JUN_KINASES_PHOSPHORYLATION_AND_ACTIVATION_MEDIATED_BY_ACTIVATED_HUMAN_TAK1"] = new_int
dict["WP_WNTBETACATENIN_SIGNALING_PATHWAY_IN_LEUKEMIA"] = new_wnt
dict["REACTOME_JNK_C_JUN_KINASES_PHOSPHORYLATION_AND_ACTIVATION_MEDIATED_BY_ACTIVATED_HUMAN_TAK1"] = new_jnk

In [42]:
# store output to gene_set_results folder
with open("./gene_set_results/sonis_dict.json", 'w') as fp:
    json.dump(dict, fp)