In [30]:
if (!require("tidyverse", quietly = TRUE)) {
  install.packages("tidyverse", quiet = TRUE, verbose = FALSE)
}

if (!require("stringr", quietly = TRUE)) {
  install.packages("tidyverse", quiet = TRUE, verbose = FALSE)
}

if (!require("data.table", quietly = TRUE)) {
  install.packages("data.table", quiet = TRUE, verbose = FALSE)
}

suppressPackageStartupMessages({
    library(tidyverse)
    library(stringr)
    library(data.table)
})

#### Loading Data

In [2]:
# Create a function to read file and select columns
read_and_select <- function(filepath, exclude_col) {
  fread(filepath) %>% select(-all_of(exclude_col))
}

# File paths and columns to exclude
filepaths <- c("../cpnds_genotyping/batch1.tsv", 
               "../cpnds_genotyping/batch2.tsv", 
               "../cpnds_genotyping/batch3.tsv")
exclude_col <- "MENDEL"

# Read files
data_list <- lapply(filepaths, function(x) read_and_select(x, exclude_col))

# Assign to variables
f1 <- data_list[[1]]
f2 <- data_list[[2]]
f3 <- data_list[[3]]

# Read phenotype and pruned data
phenotype <- read_and_select("../cpnds_genotyping/gr1_removed_high_affection.tsv", "LIAB")
pruned <- fread("../cpnds_genotyping/result.pruneddata_0.8.prune.in", header=FALSE) %>% setNames("rsid")
six_genes <- fread("../rsidSixGenesCPNDS.txt", header = FALSE) %>% setNames("rsid")
jagsetAnnot <- fread("../jag.set.annot.annot")
vep <- fread("../feature_tsv/VEP_noncanonical_included_Output.tsv") %>% select(id, cadd_phred, variant_allele) %>% rename(allele = variant_allele, marker = id) %>% na.omit()

#### Examinning Raw Post-QCed Genotype table

In [3]:
genotype <- rbind(f1,f2,f3) %>% 
distinct()

In [4]:
class(str_subset(genotype$ALLELE1, "^$|NA| "))

[1] "character"

In [5]:
#Check missing data in Allele 
sum(length(str_subset(genotype$ALLELE1, "^$|NA| ")))
sum(length(str_subset(genotype$ALLELE2, "^$|NA| ")))

[1] 207

[1] 207

In [6]:
# Store rows with missing data
dropped_rows <- genotype %>%
mutate(ALLELE1 = str_replace(ALLELE1, "^$|NA| ", NA_character_), 
       ALLELE2 = str_replace(ALLELE2, "^$|NA| ", NA_character_)) %>%
filter(is.na(ALLELE1) | is.na(ALLELE2))

# Remove Markers without Alleles 1, 2, or both
genotype <- genotype %>%
mutate(ALLELE1 = str_replace(ALLELE1, "^$|NA| ", NA_character_), 
       ALLELE2 = str_replace(ALLELE2, "^$|NA| ", NA_character_),) %>% 
drop_na(ALLELE1, ALLELE2)

In [7]:
print(paste("the percentage of subjects missing allele information is", round(n_distinct(dropped_rows$SUBJECT)*100/n_distinct(genotype$SUBJECT),2), "%")) 
print(paste("the percentage of markers missing allele information is " ,  round(n_distinct(dropped_rows$MARKER)*100/n_distinct(genotype$MARKER),2), "%"))

[1] "the percentage of subjects missing allele information is 36.33 %"
[1] "the percentage of markers missing allele information is  28.48 %"

#### identify reference allele: majority of ALLELE2 for each subject

In [8]:
reference <- genotype %>% 
group_by(MARKER) %>%
count(ALLELE2) %>% 
arrange(MARKER, desc(n)) %>%
slice_head(n = 1) %>% 
ungroup %>% 
select(-n) %>% 
rename(reference=ALLELE2)

In [9]:
genotype <- left_join(genotype, reference, by="MARKER")
pruned_genotype <- genotype %>% 
  filter(MARKER %in% pruned$rsid )

#### Convert affection status (phenotypes) to binary

In [10]:
str_subset(phenotype$phenotype, "^$|NA| ")

character(0)

In [11]:
phenotype <- phenotype %>% 
  mutate(phenotype = 
           case_when(
             grepl('healthy', AFFSTAT) ~ 0, 
             grepl('affected', AFFSTAT) ~ 1 
           )) %>% 
  select(-AFFSTAT) %>% 
  rename("subject" = "SUBJECT")

#### Joining VEP Table

In [12]:
# Function to clean marker names
clean_marker <- function(marker) {
  marker <- tolower(marker)
  marker <- gsub("gsa-|seq-", "", marker)
  marker <- dplyr::recode(marker, "ilmnseq_6:35378798" = "rs9658134")
  return(marker)
}

# Convert genotype to long format and clean marker names
genotype_long <- genotype %>% 
  pivot_longer(cols = -c(SUBJECT, MARKER), names_to = "holder", values_to = "allele") %>% 
  select(-holder) %>% 
  rename(marker = MARKER) %>% 
  mutate(marker = clean_marker(marker))

# Combine VEP with genotype in long format
combined <- left_join(genotype_long, vep, by = c("marker", "allele")) %>% 
  mutate(cadd_phred = replace_na(cadd_phred, 0)) %>% 
  rename(subject = SUBJECT)

### Filter for only variants in the 6 genes _PRKCD,PIK3R2, AGT, LRP5, CSNK1A1, PPARD_ 
* (EntrezID: 5580, 5296, 183, 4041, 1452, 5467)

In [13]:
jagsetAnnot <- jagsetAnnot %>% 
mutate(V1 = clean_marker(V1)) %>% 
filter(V3 %in% c("WNT", "IL6")) %>% 
       filter(V2 %in% c("5580", "5296", "183", "4041", "1452", "5467") ) %>% 
       mutate(symbols = case_when(
           grepl("5580", V2) ~ "PRKCD",
           grepl("5296", V2) ~ "PIK3R2",
           grepl("183", V2) ~ "AGT",
           grepl("4041", V2) ~ "LRP5",
           grepl("1452", V2) ~ "CSNK1A1",
           grepl("5467", V2) ~ "PPARD"
  )) %>% 
       setNames(c("marker", "entrezId", "pathways", "gene_symbols"))

# merge dataframes by rsid
combined <- left_join(combined, jagsetAnnot, by = "marker")

In [14]:
head(combined,1)

  subject   marker    allele cadd_phred entrezId pathways gene_symbols
1 LON400276 rs4713859 T      0          5467     WNT      PPARD

* Remove the rsIDs that were not used in the Gene Set Enrichment Analysis

In [15]:
# merge dataframes by rsid
remove <- left_join(combined %>% filter(marker  %in%  c('rs7761870','rs6457821','rs112012380','rs3823433','rs6457813','rs9658134')), jagsetAnnot, by = "marker")
remove  <- remove %>% mutate(variants = paste0(gene_symbols.x, "_", marker)) %>% select(variants)

In [16]:
variant_remove <- remove %>% 
distinct(variants)

remove_list <- as.list(variant_remove$variants)

remove_list

[[1]]
[1] "PPARD_rs7761870"

[[2]]
[1] "PPARD_rs6457821"

[[3]]
[1] "AGT_rs112012380"

[[4]]
[1] "PPARD_rs3823433"

[[5]]
[1] "PPARD_rs6457813"

[[6]]
[1] "PPARD_rs9658134"

#### Reformat Cadd_phred to capture max score for each gene (i.e. the more deleterious allele) for each allele in each subject

In [17]:
# Calculate the maximum cadd_phred score for each subject and gene_symbols pair
df_max <- combined %>% 
  group_by(subject, gene_symbols) %>% 
  summarise(max_CADD = max(cadd_phred), .groups = "drop") %>%  # .groups = "drop" ungroups the data
  pivot_wider(names_from = gene_symbols, values_from = max_CADD, names_prefix = "CADD_max_")

# Merge the maximum cadd_phred score back to the original dataframe
combined <- left_join(combined, df_max, by = "subject")

#### Combine Clinical Covariants

In [18]:
# Load high covariates file and rename 'IID' to 'subject'
cov <- fread("../cpnds_genotyping/high_covariates.tsv") %>% 
  select(-FID) %>% 
  rename(subject = IID)

In [19]:
# Identify individual without Radiation_status_N
cov%>% 
  filter(is.na(RADIATION_STATUS_N)) %>% 
  select(subject)
#Remove the only individual that does not have the radiation_status
cov <- cov %>% 
  filter(subject != 'VAN100373') %>%
  distinct()

combined <- left_join(combined %>% filter(subject != 'VAN100373'), cov, by="subject") %>%
  select(-c(cadd_phred, gene_symbols,allele, entrezId, pathways, marker))

  subject
1 VAN100373

#### Format genotype table to wider format

In [20]:
pruned_genotype_wide <- pruned_genotype_wide[,!names(pruned_genotype_wide) %in% remove_list]

ERROR: Error in eval(expr, envir, enclos): object 'pruned_genotype_wide' not found

In [21]:
pruned_genotype_wide <- pruned_genotype %>% 
  mutate(
    MARKER = clean_marker(MARKER), 
    subject = SUBJECT,
    score = case_when(
      ALLELE1 == ALLELE2 & ALLELE2 == reference ~ 0,
      ALLELE1 != ALLELE2 & ALLELE2 == reference ~ 1,
      ALLELE1 != reference & ALLELE2 != reference ~ 2
    )
  ) %>% 
  left_join(jagsetAnnot %>% select('marker', 'gene_symbols'), by = c("MARKER" = "marker")) %>%
  mutate(variants = paste0(gene_symbols, "_", MARKER)) %>%
  select(subject, variants, score) %>%
  pivot_wider(names_from = variants, values_from = score)

__For some subjects without variants,  the subject is removed from the dataset__

In [22]:
pruned_genotype_wide <- pruned_genotype_wide %>% 
na.omit()

In [34]:
sum(apply(pruned_genotype_wide, 2, function(x) x == ""))

[1] 0

In [35]:
summary(is.na(pruned_genotype_wide))

  subject        PPARD_rs4713859 LRP5_rs3736228  CSNK1A1_rs10476909
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 CSNK1A1_rs1379544 CSNK1A1_rs447950 CSNK1A1_rs414582 CSNK1A1_rs3733658
 Mode :logical     Mode :logical    Mode :logical    Mode :logical
 FALSE:192         FALSE:192        FALSE:192        FALSE:192
 CSNK1A1_rs2400891 CSNK1A1_rs10062536 LRP5_rs4988300  PPARD_rs4713858
 Mode :logical     Mode :logical      Mode :logical   Mode :logical
 FALSE:192         FALSE:192          FALSE:192       FALSE:192
 CSNK1A1_rs1363629 CSNK1A1_rs6861564 PPARD_rs4713854 CSNK1A1_rs7728256
 Mode :logical     Mode :logical     Mode :logical   Mode :logical
 FALSE:192         FALSE:192         FALSE:192       FALSE:192
 CSNK1A1_rs452366 LRP5_rs474742   CSNK1A1_rs476741 CSNK1A1_rs241280
 Mode :logical    Mode :logical   Mode :logical    Mode :logical
 FALSE:192        FALSE:192       FALSE:192        FALSE:192
 CSNK1A1_rs2454104 LRP5_rs312009   LRP5_rs314750   LRP5_rs3781590
 Mode :logical     Mode :logical   Mode :logical   Mode :logical
 FALSE:192         FALSE:192       FALSE:192       FALSE:192
 CSNK1A1_rs4409073 CSNK1A1_rs6887452 CSNK1A1_rs353237 CSNK1A1_rs10061434
 Mode :logical     Mode :logical     Mode :logical    Mode :logical
 FALSE:192         FALSE:192         FALSE:192        FALSE:192
 LRP5_rs12417014 CSNK1A1_rs12659504 LRP5_rs2306862  LRP5_rs7936582
 Mode :logical   Mode :logical      Mode :logical   Mode :logical
 FALSE:192       FALSE:192          FALSE:192       FALSE:192
 CSNK1A1_rs17724303 LRP5_rs11826287 PPARD_rs1883322 LRP5_rs632605
 Mode :logical      Mode :logical   Mode :logical   Mode :logical
 FALSE:192          FALSE:192       FALSE:192       FALSE:192
 PPARD_rs116213531 LRP5_rs75210709 LRP5_rs2508835  CSNK1A1_rs72823547
 Mode :logical     Mode :logical   Mode :logical   Mode :logical
 FALSE:192         FALSE:192       FALSE:192       FALSE:192
 LRP5_rs11228270 CSNK1A1_rs353294 PPARD_rs115128769 LRP5_rs11574424
 Mode :logical   Mode :logical    Mode :logical     Mode :logical
 FALSE:192       FALSE:192        FALSE:192         FALSE:192
 LRP5_rs660925   CSNK1A1_rs115658620 LRP5_rs77381812 CSNK1A1_rs2125130
 Mode :logical   Mode :logical       Mode :logical   Mode :logical
 FALSE:192       FALSE:192           FALSE:192       FALSE:192
 LRP5_rs72936563 CSNK1A1_rs2895862 CSNK1A1_rs353248 CSNK1A1_rs6861618
 Mode :logical   Mode :logical     Mode :logical    Mode :logical
 FALSE:192       FALSE:192         FALSE:192        FALSE:192
 CSNK1A1_rs78578633 LRP5_rs74724919 CSNK1A1_rs62378023 LRP5_rs118098503
 Mode :logical      Mode :logical   Mode :logical      Mode :logical
 FALSE:192          FALSE:192       FALSE:192          FALSE:192
 CSNK1A1_rs353241 CSNK1A1_rs111416523 LRP5_rs4988332  LRP5_rs35388122
 Mode :logical    Mode :logical       Mode :logical   Mode :logical
 FALSE:192        FALSE:192           FALSE:192       FALSE:192
 LRP5_rs113800014 CSNK1A1_rs6894391 LRP5_rs72932379 CSNK1A1_rs117311236
 Mode :logical    Mode :logical     Mode :logical   Mode :logical
 FALSE:192        FALSE:192         FALSE:192       FALSE:192
 CSNK1A1_rs35928487 CSNK1A1_rs114688286 CSNK1A1_rs62378010 LRP5_rs4988321
 Mode :logical      Mode :logical       Mode :logical      Mode :logical
 FALSE:192          FALSE:192           FALSE:192          FALSE:192
 LRP5_rs118062233 CSNK1A1_rs77489920 PPARD_rs13214733 CSNK1A1_rs72823546
 Mode :logical    Mode :logical      Mode :logical    Mode :logical
 FALSE:192        FALSE:192          FALSE:192        FALSE:192
 CSNK1A1_rs10454990 LRP5_rs76225083 LRP5_rs75177427 LRP5_rs7342161
 Mode :logical      Mode :logical   Mode :logical   Mode :logical
 FALSE:192          FALSE:192       FALSE:192       FALSE:192
 CSNK1A1_rs74474766 LRP5_rs11228184 CSNK1A1_rs75148296 CSNK1A1_rs115413638
 Mode :logical      Mode :logical   Mode :logical      Mode :logical
 FALSE:192          FALSE:192       FALSE:192          FALSE:192
 LRP5_rs74697984 CSNK1A1_rs4705346 LRP5_rs111489476 LRP5_rs118050745
 Mode :logical   Mode :logical     Mode :logical    Mode :logical
 FALSE:192       FALSE:192         FALSE:192        FALSE:192
 CSNK1A1_rs353243 LRP5_rs11602367 LRP5_rs76710454 LRP5_rs3802746
 Mode :logical    Mode :logical   Mode :logical   Mode :logical
 FALSE:192        FALSE:192       FALSE:192       FALSE:192
 CSNK1A1_rs75777785 CSNK1A1_rs73279543 PPARD_rs2016520 AGT_rs1887490
 Mode :logical      Mode :logical      Mode :logical   Mode :logical
 FALSE:192          FALSE:192          FALSE:192       FALSE:192
 AGT_rs2479131   AGT_rs3827743   PPARD_rs3798343 AGT_rs4847017
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs11122576  AGT_rs12038826  AGT_rs12731961  AGT_rs853463
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs11122577  PPARD_rs6457816 AGT_rs4847000   AGT_rs6677009
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PPARD_rs7761870 PPARD_rs2395626 PPARD_rs12203818 AGT_rs2067853
 Mode :logical   Mode :logical   Mode :logical    Mode :logical
 FALSE:192       FALSE:192       FALSE:192        FALSE:192
 AGT_rs5051      AGT_rs6698654   PPARD_rs9462081 PPARD_rs6457821
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PPARD_rs3800376 PPARD_rs7769417 AGT_rs853464    AGT_rs853469
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs6541330   AGT_rs3789647   AGT_rs12031571  AGT_rs4259658
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs1316409   AGT_rs12082061  AGT_rs1316408   AGT_rs12084401
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs2493151   PPARD_rs9658119 AGT_rs872505    AGT_rs2182574
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs3789643   PPARD_rs9368868 PPARD_rs6911817 PPARD_rs6919534
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs72759029  PPARD_rs9462088 AGT_rs111776064 AGT_rs11586594
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs77645389  PPARD_rs76626846 PPARD_rs9658130 AGT_rs2297831
 Mode :logical   Mode :logical    Mode :logical   Mode :logical
 FALSE:192       FALSE:192        FALSE:192       FALSE:192
 PPARD_rs115269427 PPARD_rs72894770 AGT_rs28359664  PPARD_rs11751895
 Mode :logical     Mode :logical    Mode :logical   Mode :logical
 FALSE:192         FALSE:192        FALSE:192       FALSE:192
 PPARD_rs9658105 AGT_rs41314282  AGT_rs3790973   PPARD_rs67056409
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PPARD_rs6907678 AGT_rs112012380 AGT_rs11122597  PPARD_rs35080860
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PPARD_rs79722771 PPARD_rs6937510 AGT_rs5049      AGT_rs61828616
 Mode :logical    Mode :logical   Mode :logical   Mode :logical
 FALSE:192        FALSE:192       FALSE:192       FALSE:192
 AGT_rs78869074  AGT_rs78983929  PPARD_rs4713872 AGT_rs943581
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PPARD_rs3823433 PPARD_rs7744392 PPARD_rs72911076 PPARD_rs7770619
 Mode :logical   Mode :logical   Mode :logical    Mode :logical
 FALSE:192       FALSE:192       FALSE:192        FALSE:192
 AGT_rs2493153   PPARD_rs4713871 PPARD_rs2395617 AGT_rs74143000
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 AGT_rs11568048  PPARD_rs10947541 PPARD_rs6910489 AGT_rs72759021
 Mode :logical   Mode :logical    Mode :logical   Mode :logical
 FALSE:192       FALSE:192        FALSE:192       FALSE:192
 PPARD_rs12525006 PPARD_rs6934083 PPARD_rs11553984 AGT_rs10158163
 Mode :logical    Mode :logical   Mode :logical    Mode :logical
 FALSE:192        FALSE:192       FALSE:192        FALSE:192
 PPARD_rs78945013 PPARD_rs6457813 PPARD_rs9658134 PRKCD_rs2564929
 Mode :logical    Mode :logical   Mode :logical   Mode :logical
 FALSE:192        FALSE:192       FALSE:192       FALSE:192
 AGT_rs4846997   PRKCD_rs1080500 PIK3R2_rs372889 PRKCD_rs13088281
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PRKCD_rs1483185 PIK3R2_rs3730179 PRKCD_rs4687712 PRKCD_rs4687717
 Mode :logical   Mode :logical    Mode :logical   Mode :logical
 FALSE:192       FALSE:192        FALSE:192       FALSE:192
 PIK3R2_rs172043 PIK3R2_rs271828 PIK3R2_rs874628 PIK3R2_rs11666281
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PRKCD_rs4328795 AGT_rs11122563  AGT_rs28359608  PIK3R2_rs2305743
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PRKCD_rs11130350 PIK3R2_rs375947 PIK3R2_rs438421 PRKCD_rs13085294
 Mode :logical    Mode :logical   Mode :logical   Mode :logical
 FALSE:192        FALSE:192       FALSE:192       FALSE:192
 AGT_rs11122562  PIK3R2_rs999813 AGT_rs4762      PRKCD_rs73076230
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PRKCD_rs10433616 PIK3R2_rs17885285 AGT_rs3889728   PIK3R2_rs17886368
 Mode :logical    Mode :logical     Mode :logical   Mode :logical
 FALSE:192        FALSE:192         FALSE:192       FALSE:192
 PIK3R2_rs17879591 PIK3R2_rs2049051 PIK3R2_rs117329793 PRKCD_rs7630325
 Mode :logical     Mode :logical    Mode :logical      Mode :logical
 FALSE:192         FALSE:192        FALSE:192          FALSE:192
 PRKCD_rs2336725 AGT_rs3761951   AGT_rs28359615  AGT_rs28359647
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:192       FALSE:192       FALSE:192       FALSE:192
 PRKCD_rs77000231 PRKCD_rs75323042 AGT_rs28359725  PRKCD_rs115659375
 Mode :logical    Mode :logical    Mode :logical   Mode :logical
 FALSE:192        FALSE:192        FALSE:192       FALSE:192
 PIK3R2_rs73001430 AGT_rs7552686   PRKCD_rs11710524 PRKCD_rs4687718
 Mode :logical     Mode :logical   Mode :logical    Mode :logical
 FALSE:192         FALSE:192       FALSE:192        FALSE:192
 PRKCD_rs116656058 PIK3R2_rs2072490 PRKCD_rs11924565 PRKCD_rs73091425
 Mode :logical     Mode :logical    Mode :logical    Mode :logical
 FALSE:192         FALSE:192        FALSE:192        FALSE:192
 PIK3R2_rs10411949 PRKCD_rs729396  AGT_rs3790960   PRKCD_rs114058530
 Mode :logical     Mode :logical   Mode :logical   Mode :logical
 FALSE:192         FALSE:192       FALSE:192       FALSE:192
 PIK3R2_rs271834 PRKCD_rs7610701 PIK3R2_rs62120362 AGT_rs6687027
 Mode :logical   Mode :logical   Mode :logical     Mode :logical
 FALSE:192       FALSE:192       FALSE:192         FALSE:192
 PIK3R2_rs412133 AGT_rs10864772  PIK3R2_rs56020911 PRKCD_rs79843306
 Mode :logical   Mode :logical   Mode :logical     Mode :logical
 FALSE:192       FALSE:192       FALSE:192         FALSE:192
 PRKCD_rs11919522 PRKCD_rs114139529 PRKCD_rs11717712 PIK3R2_rs12462974
 Mode :logical    Mode :logical     Mode :logical    Mode :logical
 FALSE:192        FALSE:192         FALSE:192        FALSE:192
 PIK3R2_rs3803919 PRKCD_rs115657945 AGT_rs2493131   PRKCD_rs6799185
 Mode :logical    Mode :logical     Mode :logical   Mode :logical
 FALSE:192        FALSE:192         FALSE:192       FALSE:192
 AGT_rs112011964 PRKCD_rs116071986 PIK3R2_rs117648604 PRKCD_rs111501004
 Mode :logical   Mode :logical     Mode :logical      Mode :logical
 FALSE:192       FALSE:192         FALSE:192          FALSE:192
 PIK3R2_rs11670370 AGT_rs17733009  PIK3R2_rs56022120 PIK3R2_rs79268593
 Mode :logical     Mode :logical   Mode :logical     Mode :logical
 FALSE:192         FALSE:192       FALSE:192         FALSE:192
 AGT_rs11558606  PRKCD_rs62255930 PIK3R2_rs61740749 PRKCD_rs750527
 Mode :logical   Mode :logical    Mode :logical     Mode :logical
 FALSE:192       FALSE:192        FALSE:192         FALSE:192
 PRKCD_rs1004807
 Mode :logical
 FALSE:192

#### Join previous combined table with pruned genotype table

In [24]:
class(pruned_genotype_wide$LRP5_rs3736228)

[1] "numeric"

In [25]:
pruned_combined <- pruned_genotype_wide  %>% 
left_join(combined, by="subject") %>% 
left_join(phenotype, by="subject")

In [26]:
sum(is.na(pruned_combined))

[1] 0

#### Remove redundancy

In [27]:
pruned_combined <- pruned_combined %>% 
distinct() %>% 
select(-subject)

In [36]:
pruned_combined

    PPARD_rs4713859 LRP5_rs3736228 CSNK1A1_rs10476909 CSNK1A1_rs1379544
1   0               0              1                  1
2   0               1              1                  0
3   0               0              0                  1
4   0               0              1                  1
5   1               1              1                  2
6   0               0              1                  1
7   0               0              0                  1
8   0               0              0                  1
9   0               0              0                  1
10  0               0              1                  1
11  0               0              1                  1
12  0               0              0                  1
13  1               0              0                  1
14  0               1              1                  1
15  0               0              0                  0
16  0               0              1                  0
17  0               0              0                  0
18  1               0              1                  0
19  2               0              2                  1
20  0               0              1                  0
21  0               0              2                  0
22  0               1              0                  0
23  0               0              0                  2
24  0               2              1                  1
25  0               0              0                  0
26  0               0              0                  0
27  0               0              0                  1
28  0               1              0                  1
29  0               0              0                  1
30  0               0              0                  1
<U+22EE>   <U+22EE>        <U+22EE>       <U+22EE>           <U+22EE>
163 0               0              0                  0
164 1               0              0                  1
165 0               0              0                  1
166 0               0              2                  1
167 1               0              1                  0
168 0               0              0                  0
169 0               0              0                  1
170 0               0              0                  1
171 1               0              1                  1
172 0               0              0                  1
173 0               0              0                  0
174 0               0              0                  1
175 1               0              0                  1
176 0               0              1                  2
177 0               0              0                  1
178 0               0              1                  2
179 0               1              0                  0
180 1               0              0                  2
181 1               0              0                  0
182 0               0              0                  1
183 1               0              0                  1
184 0               2              0                  1
185 0               0              0                  1
186 0               0              0                  2
187 1               0              2                  1
188 0               0              1                  1
189 1               0              1                  0
190 0               0              0                  2
191 0               0              0                  0
192 0               0              1                  2
    CSNK1A1_rs447950 CSNK1A1_rs414582 CSNK1A1_rs3733658 CSNK1A1_rs2400891
1   0                0                1                 1
2   1                0                0                 0
3   1                1                1                 1
4   0                0                2                 2
5   0                0                2                 2
6   1                0                0                 1
7   0                0                1                 1
8   0                0                1                 1
9   0                1                1                 1
10  1                0                1                 1
11  1                0                1                 1
12  1                0                1                 1
13  1                0                1                 1
14  0                0                1                 1
15  1                0                0                 0
16  0                0                0                 1
17  1                0                0                 0
18  1                0                0                 0
19  0                1                0                 0
20  1                0                0                 0
21  1                1                1                 1
22  0                0                0                 0
23  0                0                2                 2
24  0                0                1                 1
25  1                0                0                 0
26  1                0                1                 0
27  0                0                1                 1
28  1                0                1                 1
29  1                0                1                 1
30  1                0                0                 1
<U+22EE>   <U+22EE>         <U+22EE>         <U+22EE>          <U+22EE>
163 0                1                0                 0
164 1                1                2                 2
165 1                0                1                 1
166 2                0                1                 1
167 1                0                0                 0
168 1                0                0                 0
169 0                0                0                 1
170 1                0                1                 1
171 1                0                2                 2
172 1                0                1                 1
173 1                1                1                 1
174 1                0                1                 1
175 1                0                1                 1
176 0                0                2                 2
177 0                0                2                 1
178 0                0                2                 2
179 1                0                0                 0
180 0                1                1                 1
181 1                0                0                 0
182 0                0                1                 1
183 1                0                1                 1
184 0                0                1                 1
185 2                0                1                 1
186 1                0                2                 2
187 1                1                0                 0
188 0                0                0                 1
189 0                0                1                 1
190 1                0                2                 2
191 1                1                0                 0
192 0                0                2                 2
    CSNK1A1_rs10062536 LRP5_rs4988300 <U+22EF>        CADD_max_PPARD CADD_max_PRKCD
1   0                  0              <U+22EF> 13.94           6.272
2   0                  1              <U+22EF> 13.94           6.272
3   1                  0              <U+22EF> 13.94           6.272
4   0                  1              <U+22EF> 13.94           6.272
5   0                  2              <U+22EF> 13.94           6.272
6   0                  1              <U+22EF> 13.94           6.272
7   0                  1              <U+22EF> 13.94           6.272
8   0                  1              <U+22EF> 13.94           6.272
9   0                  0              <U+22EF> 13.94          12.370
10  0                  1              <U+22EF> 13.94          12.370
11  0                  0              <U+22EF> 13.94           6.272
12  0                  1              <U+22EF> 13.94          12.370
13  1                  1              <U+22EF> 13.94          12.370
14  0                  2              <U+22EF> 13.94          12.370
15  1                  0              <U+22EF> 13.94           6.272
16  0                  1              <U+22EF> 13.94          12.370
17  0                  0              <U+22EF> 13.94          12.370
18  0                  1              <U+22EF> 13.94           6.272
19  1                  2              <U+22EF> 13.94           6.272
20  0                  2              <U+22EF> 13.94           6.272
21  1                  0              <U+22EF> 13.94          12.370
22  0                  1              <U+22EF> 13.94          12.370
23  0                  0              <U+22EF> 13.94          12.370
24  0                  1              <U+22EF> 13.94          12.370
25  0                  1              <U+22EF> 13.94           8.324
26  0                  2              <U+22EF> 13.94           6.272
27  0                  1              <U+22EF> 13.94          12.370
28  0                  0              <U+22EF> 13.94           8.324
29  0                  2              <U+22EF> 13.94          12.370
30  0                  1              <U+22EF> 13.94          12.370
<U+22EE>   <U+22EE>           <U+22EE>       <U+22F1> <U+22EE>       <U+22EE>
163 1                  0              <U+22EF> 13.94          12.370
164 1                  0              <U+22EF> 13.94           6.272
165 0                  0              <U+22EF> 13.94          12.370
166 0                  2              <U+22EF> 13.94          12.370
167 0                  2              <U+22EF> 13.94          12.370
168 0                  2              <U+22EF> 13.94           6.272
169 0                  1              <U+22EF> 13.94          12.370
170 0                  1              <U+22EF> 13.94           8.324
171 0                  0              <U+22EF> 13.94           6.272
172 0                  2              <U+22EF> 13.94          12.370
173 0                  0              <U+22EF> 13.94           6.272
174 0                  1              <U+22EF> 13.94           8.324
175 1                  0              <U+22EF> 13.94          12.370
176 0                  1              <U+22EF> 13.94          12.370
177 0                  1              <U+22EF> 13.94           6.272
178 0                  1              <U+22EF> 13.94          12.370
179 0                  1              <U+22EF> 13.94           6.272
180 0                  1              <U+22EF> 13.94           6.272
181 0                  1              <U+22EF> 13.94          12.370
182 0                  1              <U+22EF> 13.94           6.272
183 0                  1              <U+22EF> 13.94          12.370
184 0                  2              <U+22EF> 13.94          12.370
185 0                  1              <U+22EF> 13.94          12.370
186 0                  1              <U+22EF> 13.94          12.370
187 1                  2              <U+22EF> 13.94           6.272
188 0                  1              <U+22EF> 13.94           6.272
189 1                  1              <U+22EF> 13.94           6.272
190 0                  1              <U+22EF> 13.94           6.272
191 0                  1              <U+22EF> 13.94          12.370
192 0                  2              <U+22EF> 13.94           8.324
    SEX_N_MALE RADIATION_STATUS_N AGE_MTX_INITIATION_YEAR PC1
1   0          0                  10.9835616              -0.00819109
2   0          0                   7.9972678              -0.00818886
3   1          1                  16.4986301              -0.00045870
4   0          0                   1.8027397              -0.00804984
5   0          0                  10.8657534              -0.00913200
6   1          1                   1.8794521              -0.00782076
7   1          0                   1.2240437              -0.00858358
8   0          0                   2.4767123              -0.00556460
9   0          0                   4.9369863              -0.00838257
10  0          0                   6.7616438              -0.00872479
11  0          0                   3.3506849              -0.00855464
12  1          0                   3.9397260              -0.00840396
13  0          0                   2.5983607              -0.00856159
14  1          0                   5.4219178              -0.00812101
15  0          0                   2.2404372              -0.01190060
16  1          0                   3.3726027              -0.00819998
17  0          0                   2.7671233              -0.00825970
18  0          0                   2.8794521              -0.00795066
19  0          1                  15.5013699               0.03710250
20  0          1                  10.7486339              -0.00795449
21  1          0                   4.1967213              -0.00732181
22  0          0                   0.7068493              -0.00803501
23  0          0                   1.0849315              -0.00884421
24  0          0                   2.5013699              -0.00846603
25  1          0                   4.3150685              -0.00858995
26  1          0                   3.2082192               0.01362010
27  1          0                   1.3251366              -0.00786685
28  1          0                   8.2684932              -0.00632105
29  1          0                   2.9644809              -0.00833623
30  1          0                   7.4246575              -0.00826057
<U+22EE>   <U+22EE>   <U+22EE>           <U+22EE>                <U+22EE>
163 1          0                   0.9232877              -0.00688132
164 1          1                   7.2575342              -0.00812921
165 0          1                   8.0821918              -0.00831677
166 0          0                   1.8191781              -0.00768092
167 0          0                   1.8739726              -0.00829085
168 1          1                   3.9232877              -0.00808082
169 1          0                   9.1479452              -0.00660242
170 1          1                  12.1123288              -0.00551122
171 0          0                   3.5643836              -0.00625622
172 1          0                   5.3972603              -0.00746816
173 0          0                   3.9013699              -0.00607484
174 1          0                   9.5013699              -0.00873081
175 1          0                   1.1095890              -0.01003210
176 0          0                   3.9781421              -0.00900871
177 0          0                   2.6448087              -0.00835162
178 0          0                   2.7808219              -0.00779945
179 1          0                  11.2493151              -0.00731413
180 0          1                   3.9561644               0.01554750
181 1          0                  16.8739726              -0.00571795
182 0          1                  11.0874317              -0.00811479
183 0          0                   3.5506849              -0.00912160
184 1          1                   2.8547945              -0.00783766
185 0          0                  11.8520548              -0.00869082
186 0          1                   2.6912568              -0.00799837
187 1          0                   2.2684932               0.04004450
188 0          0                  13.7890411              -0.01150490
189 1          1                   3.3671233              -0.01017120
190 1          1                  10.4849315              -0.00920028
191 1          0                   5.5068493              -0.00881339
192 0          0                   4.0821918              -0.00629637
    PC2         PC3          PC4          phenotype
1   -0.01867980  0.005814860 -0.007582830 0
2   -0.01854910  0.008773370 -0.008294950 0
3   -0.01312030  0.008233090  0.012657200 0
4   -0.01916960  0.007358760 -0.009525170 0
5   -0.01244720 -0.005811660 -0.005802180 0
6   -0.01916950  0.008494100 -0.007924700 0
7   -0.01866460  0.007065230 -0.006844470 0
8   -0.01578990  0.008940870  0.012408200 0
9   -0.01868390  0.008829320 -0.006979120 0
10  -0.01845700  0.007811300 -0.005465440 0
11  -0.01859260  0.005720090 -0.008331550 1
12  -0.01824510  0.006203680 -0.004700670 0
13  -0.01879710  0.007115650 -0.005547120 0
14  -0.01869690  0.007185800 -0.006213900 0
15   0.02829600  0.010820000 -0.000659291 1
16  -0.00277273 -0.036058400 -0.001394890 1
17  -0.01819540  0.007120580 -0.007504170 1
18  -0.01864890  0.008211810 -0.006147330 1
19   0.00347820  0.000130639 -0.001022200 1
20  -0.01890570  0.008196860 -0.007652360 0
21  -0.01768750  0.008802610 -0.008430310 0
22  -0.01809940  0.004521950 -0.005700390 0
23  -0.01869040  0.008416860 -0.008618830 0
24  -0.01816680  0.007339880 -0.005706590 0
25  -0.01860190  0.007321100 -0.007585400 0
26  -0.00137353 -0.013097400 -0.001256940 0
27  -0.01752110  0.006790520 -0.007682670 0
28  -0.00633998  0.004132350  0.054965600 0
29  -0.01837600  0.007582520 -0.007358140 0
30  -0.01861650  0.007683630 -0.007665540 1
<U+22EE>   <U+22EE>    <U+22EE>     <U+22EE>     <U+22EE>
163 -0.01736580  9.10221e-03 -0.000909423 1
164 -0.01814220  8.73050e-03 -0.007479370 1
165 -0.01833250  7.47971e-03 -0.005320500 0
166 -0.01891960  7.21787e-03 -0.004709850 1
167 -0.01929010  6.18761e-03 -0.007284590 0
168 -0.01807040  6.77473e-03 -0.009296330 1
169 -0.01723520  8.77405e-03  0.001148500 0
170  0.00173626  6.71101e-03  0.078147400 1
171 -0.00666728  6.30942e-03  0.055763800 0
172 -0.01781970  8.33214e-03 -0.009020070 1
173 -0.01285560  7.57208e-03  0.023367000 0
174 -0.01888000  6.86142e-03 -0.007040420 1
175  0.00505723  9.62043e-03 -0.004205290 1
176 -0.01757180  7.01670e-03 -0.005674250 0
177 -0.01935770  6.76438e-03 -0.007111180 0
178 -0.01889000  7.81605e-03 -0.009495380 0
179 -0.01833870  8.74873e-03 -0.005718950 1
180 -0.00685443  3.65633e-03 -0.001575400 0
181 -0.00278587 -2.98994e-02 -0.002466800 1
182 -0.01878350  8.85716e-03 -0.006613870 0
183 -0.01731440  5.27717e-03 -0.006950060 0
184 -0.01744580  8.90698e-03 -0.004235440 0
185 -0.01859940  7.03777e-03 -0.005323050 0
186 -0.01834700  8.94435e-03 -0.008052360 1
187  0.00558136  3.31009e-05 -0.001345530 0
188  0.02796980  1.10106e-02  0.003176450 0
189  0.00590383  9.75014e-03 -0.002823300 0
190 -0.01745350  5.20600e-03 -0.006066480 0
191 -0.01896420  7.45907e-03 -0.007980430 0
192 -0.01795200  9.31034e-03  0.002128060 0

#### Save pruned_features_table

In [37]:
write.table(pruned_combined , "../feature_tsv/feature_pruned_subject_removed.tsv", sep = '\t', row.names = FALSE)